import type { NextPage } from "next";
import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { Layout } from "components/Layout";
import { Autocomplete, TextField } from "@mui/material";
import { Converter } from "components/Converter";
import { useEffect, useState } from "react";
import { SetStateAction } from "react";

const Home: NextPage = ({ currencies }: any) => {
  const { t } = useTranslation("common");
  const [fromCurrency, setFromCurrency] = useState("");
  const [toCurrency, setToCurrency] = useState("");
  const [fromExchange, setFromExChange] = useState(0);
  const [toExchange, setToExchange] = useState(0);
  const [currencyValue, setCurrencyValue] = useState<
    SetStateAction<Promise<number>> | any
  >(0);
  useEffect(() => {
    if (toCurrency !== "" && toCurrency.length > 2) {
      const fetchData = async () => {
        const response = await fetch(`http://localhost:3000/api`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Accept: "application/json",
          },
          body: JSON.stringify({
            code: fromCurrency.toLowerCase(),
            to: toCurrency.toLowerCase(),
          }),
        });
        const data = await response.json();
        console.log("Data : ", data[toCurrency.toLowerCase()]);
        return setCurrencyValue(data[toCurrency.toLowerCase()]);
      };

      setCurrencyValue(fetchData());
      console.log("use", typeof fetchData());
    }
  }, [toCurrency]);

  return (
    <Layout>
      <Head>
        <title>
          {t("appName")} - {t("Pages.Home")}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Converter
        currencies={currencies}
        fromCurrency={fromCurrency}
        toCurrency={toCurrency}
        fromExchange={fromExchange}
        toExchange={toExchange}
        setFromCurrency={setFromCurrency}
        setToCurrency={setToCurrency}
        setFromExchange={setFromExChange}
        setToExchange={setToExchange}
        currencyValue={currencyValue}
      />
    </Layout>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  const response = await fetch(`http://localhost:3000/api/currencies`);
  const currencies = await response.json();
  return {
    props: {
      currencies,
      ...(await serverSideTranslations(locale, ["common"])),
      // Will be passed to the page component as props
    },
  };
}

export default Home;
